In [4]:
import numpy as np

## Creating Arrays

In [6]:
arr = np.array([1, 2, 3])
arr.ndim

1

In [5]:
arr = np.array([
    [1, 2, 3], 
    [3, 5, 7]
])
arr.ndim

2

In [7]:
arr = np.array( [
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
]
)
arr.ndim

3

In [11]:
np.zeros((4, 2, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [12]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((5, 5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [16]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [18]:
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Pseudo-Random Numbers 

In [29]:
np.random.seed(44)
np.random.rand(5, 2)

array([[0.83484215, 0.1047961 ],
       [0.74464048, 0.36050084],
       [0.35931084, 0.60923838],
       [0.39377955, 0.40907261],
       [0.50990241, 0.71014799]])

In [21]:
np.random.randn(5)

array([ 0.74645589,  1.0214385 , -0.5456349 ,  1.3687597 , -0.40906499])

In [22]:
np.random.randint(1, 10, (3, 3))

array([[2, 7, 9],
       [7, 1, 5],
       [5, 3, 7]])

In [27]:
np.random.seed(14)
np.random.randint(1, 10, (3, 3))

array([[9, 7, 8],
       [7, 1, 9],
       [8, 7, 1]])

In [40]:
np.random.seed(0)
print(np.random.randn(5))
np.random.seed(0)
print(np.random.randn(5))
print(np.random.randn(5))
print(np.random.randn(5))

[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799]
[-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
[0.14404357 1.45427351 0.76103773 0.12167502 0.44386323]


In [33]:
np.random.randn(5)

array([0.14404357, 1.45427351, 0.76103773, 0.12167502, 0.44386323])

In [41]:
arr = np.random.randn(5)

## Attributes and Methods

In [42]:
arr.dtype

dtype('float64')

In [43]:
np.random.randint(1, 10, (3, 3)).dtype

dtype('int32')

In [44]:
np.random.randint(1, 10, (3, 3)).ndim

2

In [45]:
arr = np.random.randint(1, 10, (5, 3))

In [46]:
arr

array([[2, 2, 8],
       [4, 7, 8],
       [3, 1, 4],
       [6, 5, 5],
       [7, 5, 5]])

In [47]:
arr.shape

(5, 3)

In [50]:
np.random.randint(1, 100, 8).reshape(4, 3)

ValueError: cannot reshape array of size 8 into shape (4,3)

In [53]:
np.random.randint(1, 100, 8).reshape(4, 2).T

array([[63, 95, 83, 21],
       [36, 68, 47, 82]])

In [54]:
arr

array([[2, 2, 8],
       [4, 7, 8],
       [3, 1, 4],
       [6, 5, 5],
       [7, 5, 5]])

In [56]:
arr.max(axis=1)

array([8, 8, 4, 6, 7])

In [58]:
arr.argmin(axis=1)

array([0, 0, 1, 1, 1], dtype=int32)

In [59]:
arr.argmax(axis=1)

array([2, 2, 2, 0, 0], dtype=int32)

In [62]:
arr.min(axis=0)

array([2, 1, 4])

In [63]:
arr.shape

(5, 3)

In [64]:
arr.itemsize

4

## Fetching Data

In [65]:
arr = np.arange(1, 10)

In [66]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[3]

4

In [72]:
np.random.seed(0)
arr2d = np.random.randint(1, 100, (6, 4))
arr2d

array([[45, 48, 65, 68],
       [68, 10, 84, 22],
       [37, 88, 71, 89],
       [89, 13, 59, 66],
       [40, 88, 47, 89],
       [82, 38, 26, 78]])

In [74]:
arr2d[2][1]

88

In [75]:
arr2d[2, 1]

88

In [76]:
arr2d[2:4, 1:3]

array([[88, 71],
       [13, 59]])

In [77]:
arr2d[-2:, :]

array([[40, 88, 47, 89],
       [82, 38, 26, 78]])

In [83]:
arr2d[[3, 1, 5]]

array([[89, 13, 59, 66],
       [68, 10, 84, 22],
       [82, 38, 26, 78]])

In [81]:
arr2d[(1, 3, 4)]

22

In [84]:
arr  = np.arange(1, 11)

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[arr >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [87]:
arr >= 5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
arr[arr > 10]

array([], dtype=int32)

## Arithmetic Operations

In [91]:
arr1 = np.random.randint(1, 4, 5)
arr1

array([2, 3, 1, 2, 2])

In [92]:
arr2 = np.random.randint(1, 10, 5)
arr2

array([1, 5, 8, 4, 3])

In [93]:
arr1 + arr2

array([3, 8, 9, 6, 5])

In [94]:
arr1 - arr2

array([ 1, -2, -7, -2, -1])

In [95]:
arr1 * arr2

array([ 2, 15,  8,  8,  6])

In [97]:
arr1 = np.arange(1, 7).reshape(3, 2)
arr2 = np.arange(1, 7).reshape(3, 2)

In [98]:
arr1, arr2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [99]:
arr1 + arr2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [101]:
arr2 = np.arange(1, 5).reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [102]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [103]:
arr2 = np.array([1, 2])

In [104]:
arr1.shape, arr2.shape

((3, 2), (2,))

In [105]:
arr1 + arr2

array([[2, 4],
       [4, 6],
       [6, 8]])

In [108]:
arr1 = np.array([1, 2, 3]).reshape(3, 1)
arr2 = np.array([1, 2, 3])

In [109]:
arr1

array([[1],
       [2],
       [3]])

In [110]:
arr2

array([1, 2, 3])

In [111]:
arr1+ arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [112]:
# (3, 1) (1, 3)

# arr1 => (3, 3)
# arr2 => (3, 3)

# arr1 =>
# [
#     [1, 1, 1], 
#     [2, 2, 2], 
#     [3, 3, 3]
# ]

# arr2 =>
# [
#     [1, 2, 3], 
#     [1, 2, 3], 
#     [1, 2, 3]
# ]

In [113]:
arr1 = np.zeros((4, 2))
arr2 = np.ones((4, 3))
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,2) (4,3) 

In [114]:
arr1 = np.arange(1, 5)

In [115]:
arr1

array([1, 2, 3, 4])

In [116]:
arr1 + 2

array([3, 4, 5, 6])

In [117]:
arr1 = np.arange(5)
arr2 = np.arange(5)
arr1 / arr2

<ipython-input-117-ba00d4356f5d>:3: RuntimeWarning: invalid value encountered in true_divide
  arr1 / arr2


array([nan,  1.,  1.,  1.,  1.])

In [118]:
 1/ 0

ZeroDivisionError: division by zero

## Copy Data

In [130]:
arr1 = np.arange(5)
arr2 = arr1.copy()
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [131]:
arr2[0] = 10

In [132]:
arr2

array([10,  1,  2,  3,  4])

In [133]:
arr1

array([0, 1, 2, 3, 4])

In [124]:
l1 = [1, 2, 3]
l2 = l1[:]
l2[1] = 5
l1, l2

([1, 2, 3], [1, 5, 3])

In [137]:
arr1 = np.arange(5)
arr2 = arr1[0:2].copy()
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0, 1]))

In [138]:
arr2[0] = 5
arr1, arr2

(array([0, 1, 2, 3, 4]), array([5, 1]))

## Mathematical Functions

In [139]:
arr1

array([0, 1, 2, 3, 4])

In [140]:
arr1.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [141]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [142]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [143]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [11]:
# For More Mathematical Functions - https://numpy.org/doc/stable/reference/routines.math.html

## Dot Product and Transpose

In [144]:
arr1 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

In [146]:
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [148]:
arr1.dot(arr1.T)

array([[14, 32],
       [32, 77]])

## Sorting

In [5]:
arr1 = np.array([5, 4, 9, 1, 2])

In [150]:
np.sort(arr1)

array([1, 2, 4, 5, 9])

In [6]:
np.sort(arr1)[::-1] # Sorting in Reverse Order

array([9, 5, 4, 2, 1])

In [9]:
arr1 = np.array([
    [11, 8, 3], 
    [1, 0, 16]
])
np.sort(arr1)

array([[ 3,  8, 11],
       [ 0,  1, 16]])

In [10]:
np.sort(arr1)[:,::-1] # Sorting in Reverse Order

array([[11,  8,  3],
       [16,  1,  0]])

## Convert Image to NumPy Array

In [158]:
from matplotlib.image import imread

In [159]:
kitten = imread('images/a.jpg')

In [161]:
type(kitten)

numpy.ndarray

In [162]:
kitten

array([[[61, 72, 55],
        [58, 69, 52],
        [57, 68, 51],
        ...,
        [22, 57, 37],
        [21, 56, 36],
        [21, 56, 36]],

       [[59, 70, 53],
        [58, 69, 52],
        [58, 69, 52],
        ...,
        [20, 58, 37],
        [21, 56, 36],
        [19, 57, 36]],

       [[55, 66, 49],
        [54, 65, 48],
        [56, 67, 50],
        ...,
        [19, 58, 39],
        [20, 57, 39],
        [18, 57, 38]],

       ...,

       [[34, 44, 35],
        [33, 43, 34],
        [33, 43, 34],
        ...,
        [24, 28, 29],
        [24, 28, 29],
        [24, 28, 29]],

       [[35, 45, 36],
        [35, 45, 36],
        [34, 44, 35],
        ...,
        [24, 28, 29],
        [24, 28, 29],
        [24, 28, 29]],

       [[37, 47, 38],
        [36, 46, 37],
        [35, 45, 36],
        ...,
        [24, 28, 29],
        [24, 28, 29],
        [24, 28, 29]]], dtype=uint8)

In [166]:
kitten.ndim, kitten.size

(3, 72000000)

In [164]:
arr1 = np.arange(0, 10)

In [165]:
arr1.size

10